### ISSUE TITLE
Can't open volumetric data via S3 (works locally!)

### ISSUE THREAD

**Issue by constantinpape** [ome/napari-ome-zarr#38]
Opening the data generated with https://github.com/ome/ome-ngff-prototypes/tree/main/workflows/mobie-example via s3 does not work. Opening it locally works without issues.

Here's napari when opening it locally via `$ napari Covid19-S4-Area2/images/ome-zarr/raw.ome.zarr`:
![image](https://user-images.githubusercontent.com/4263537/158622537-b240f828-42dd-4268-baf5-8ca9eb829868.png)

And here's napari when opening it from s3, eitther with
`$ napari https://s3.embl.de/i2k-2020/project-ome-zarr/Covid19-S4-Area2/images/ome-zarr/raw.ome.zarr` or `napari https://uk1s3.embassy.ebi.ac.uk/bia-mobie-test/Covid19-S4-Area2/images/ome-zarr/raw.ome.zarr`. (The dataset is available both via the EMBL-Heidelberg and EBI S3):
![image](https://user-images.githubusercontent.com/4263537/158623055-1ca4c47a-89e0-4402-8bf7-5b3cd61ecfb4.png)

Note that the data can be accessed from these s3 stores via BigDataViewer (`Plugin->BigDataViewer->OME ZARR->Open OME ZARR from S3...`, needs MoBIE update site and latest version of it).

**Comment by sbesson** [comment]
@constantinpape running `napari -vv` I see that the engine is trying to load chunks e.g. https://uk1s3.embassy.ebi.ac.uk/bia-mobie-test/Covid19-S4-Area2/images/ome-zarr/raw.ome.zarr/s0/0/0/0 However there does not seem to be any such object in the bucket which likely explains the black planes.

Running`aws --endpoint-url https://uk1s3.embassy.ebi.ac.uk s3 ls s3://bia-mobie-test/Covid19-S4-Area2/images/ome-zarr/raw.ome.zarr/s0/`, it looks like the chunks are `.` separated rather than `/` separated. Is that also the case in your local version?

**Comment by constantinpape** [comment]
@sbesson you're right, the chunks are `.` separated. Thanks for noticing. I know why this happens and it's only sort-of my fault...
I will open another issue in `ome-zarr-py` about this.

**Comment by constantinpape** [comment]
Ok, nvmd I confused something, it's completely my fault :D. I will fix it and reupload the data.
